import UIButtonDemo from './UIButton/demo';
import UICheckboxDemo from './UICheckbox/demo';
import UICheckboxGroupDemo from './UICheckboxGroup/demo';
import UIDialogDemo from './UIDialog/demo';
import UIFittedTextDemo from './UIFittedText/demo';
import UIImageDemo from './UIImage/demo';
import UIListDemo from './UIList/demo';
import UIModalDemo from './UIModal/demo';
import UINotificationDemo from './UINotification/demo';
import UIPopoverDemo from './UIPopover/demo';
import UIProgressDemo from './UIProgress/demo';
import UIProgressiveDisclosureDemo from './UIProgressiveDisclosure/demo';
import UIRadioDemo from './UIRadio/demo';
import UITableDemo from './UITable/demo';
import UITokenizedInputDemo from './UITokenizedInput/demo';
import UITypeaheadInputDemo from './UITypeaheadInput/demo';
import React from 'react';
import ReactDOM from 'react-dom';

ReactDOM.render(<UIButtonDemo />, document.getElementById('ui-button'));
ReactDOM.render(<UICheckboxDemo />, document.getElementById('ui-checkbox'));
ReactDOM.render(<UICheckboxGroupDemo />, document.getElementById('ui-checkbox-group'));
ReactDOM.render(<UIDialogDemo />, document.getElementById('ui-dialog'));
ReactDOM.render(<UIFittedTextDemo />, document.getElementById('ui-fitted-text'));
ReactDOM.render(<UIImageDemo />, document.getElementById('ui-image'));
ReactDOM.render(<UIListDemo />, document.getElementById('ui-list'));
ReactDOM.render(<UIModalDemo />, document.getElementById('ui-modal'));
ReactDOM.render(<UINotificationDemo />, document.getElementById('ui-notification'));
ReactDOM.render(<UIPopoverDemo />, document.getElementById('ui-popover'));
ReactDOM.render(<UIProgressDemo />, document.getElementById('ui-progress'));
ReactDOM.render(<UIProgressiveDisclosureDemo />, document.getElementById('ui-disclosure'));
ReactDOM.render(<UIRadioDemo />, document.getElementById('ui-radio'));
ReactDOM.render(<UITableDemo />, document.getElementById('ui-table'));
ReactDOM.render(<UITokenizedInputDemo />, document.getElementById('ui-tokenfield'));
ReactDOM.render(<UITypeaheadInputDemo />, document.getElementById('ui-typeahead'));
