import UIButtonDemo from './UIButton/demo';
import UICheckboxDemo from './UICheckbox/demo';
import UICheckboxGroupDemo from './UICheckboxGroup/demo';
import UIDialogDemo from './UIDialog/demo';
import UIFittedTextDemo from './UIFittedText/demo';
import UIImageDemo from './UIImage/demo';
import UIListDemo from './UIList/demo';
import UIModalDemo from './UIModal/demo';
import UINotificationDemo from './UINotification/demo';
import UIPopoverDemo from './UIPopover/demo';
import UIProgressDemo from './UIProgress/demo';
import UIProgressiveDisclosureDemo from './UIProgressiveDisclosure/demo';
import UIRadioDemo from './UIRadio/demo';
import UITableDemo from './UITable/demo';
import UITokenizedInputDemo from './UITokenizedInput/demo';
import UITypeaheadInputDemo from './UITypeaheadInput/demo';
import React from 'react';

React.render(<UIButtonDemo />, document.getElementById('ui-button'));
React.render(<UICheckboxDemo />, document.getElementById('ui-checkbox'));
React.render(<UICheckboxGroupDemo />, document.getElementById('ui-checkbox-group'));
React.render(<UIDialogDemo />, document.getElementById('ui-dialog'));
React.render(<UIFittedTextDemo />, document.getElementById('ui-fitted-text'));
React.render(<UIImageDemo />, document.getElementById('ui-image'));
React.render(<UIListDemo />, document.getElementById('ui-list'));
React.render(<UIModalDemo />, document.getElementById('ui-modal'));
React.render(<UINotificationDemo />, document.getElementById('ui-notification'));
React.render(<UIPopoverDemo />, document.getElementById('ui-popover'));
React.render(<UIProgressDemo />, document.getElementById('ui-progress'));
React.render(<UIProgressiveDisclosureDemo />, document.getElementById('ui-disclosure'));
React.render(<UIRadioDemo />, document.getElementById('ui-radio'));
React.render(<UITableDemo />, document.getElementById('ui-table'));
React.render(<UITokenizedInputDemo />, document.getElementById('ui-tokenfield'));
React.render(<UITypeaheadInputDemo />, document.getElementById('ui-typeahead'));
