import UITypeahead from './index';
import UIView from '../UIView';
import React from 'react';
import _ from 'lodash';

export default class UITypeaheadDemo extends UIView {
    initialState() {
        return {
            countries: [
                'Afghanistan',
                'Albania',
                'Algeria',
                'American Samoa',
                'Andorra',
                'Angola',
                'Anguilla',
                'Antarctica',
                'Antigua and Barbuda',
                'Argentina',
                'Armenia',
                'Aruba',
                'Australia',
                'Austria',
                'Azerbaijan',
                'Bahamas',
                'Bahrain',
                'Bangladesh',
                'Barbados',
                'Belarus',
                'Belgium',
                'Belize',
                'Benin',
                'Bermuda',
                'Bhutan',
                'Bolivia',
                'Bosnia and Herzegovina',
                'Botswana',
                'Bouvet Island',
                'Brazil',
                'British Indian Ocean Territory',
                'Brunei Darussalam',
                'Bulgaria',
                'Burkina Faso',
                'Burundi',
                'Cambodia',
                'Cameroon',
                'Canada',
                'Cape Verde',
                'Caribbean Netherlands',
                'Cayman Islands',
                'Central African Republic',
                'Chad',
                'Chile',
                'China',
                'Christmas Island',
                'Cocos (Keeling) Islands',
                'Colombia',
                'Comoros',
                'Congo',
                'Congo, Democratic Republic of',
                'Cook Islands',
                'Costa Rica',
                'Croatia',
                'Cuba',
                'CuraÁao',
                'Cyprus',
                'Czech Republic',
                'CÙte d\'Ivoire',
                'Denmark',
                'Djibouti',
                'Dominica',
                'Dominican Republic',
                'Ecuador',
                'Egypt',
                'El Salvador',
                'Equatorial Guinea',
                'Eritrea',
                'Estonia',
                'Ethiopia',
                'Falkland Islands',
                'Faroe Islands',
                'Fiji',
                'Finland',
                'France',
                'French Guiana',
                'French Polynesia',
                'French Southern Territories',
                'Gabon',
                'Gambia',
                'Georgia',
                'Germany',
                'Ghana',
                'Gibraltar',
                'Greece',
                'Greenland',
                'Grenada',
                'Guadeloupe',
                'Guam',
                'Guatemala',
                'Guernsey',
                'Guinea',
                'Guinea-Bissau',
                'Guyana',
                'Haiti',
                'Heard and McDonald Islands',
                'Honduras',
                'Hong Kong',
                'Hungary',
                'Iceland',
                'India',
                'Indonesia',
                'Iran',
                'Iraq',
                'Ireland',
                'Isle of Man',
                'Israel',
                'Italy',
                'Jamaica',
                'Japan',
                'Jersey',
                'Jordan',
                'Kazakhstan',
                'Kenya',
                'Kiribati',
                'Kuwait',
                'Kyrgyzstan',
                'Lao People\'s Democratic Republic',
                'Latvia',
                'Lebanon',
                'Lesotho',
                'Liberia',
                'Libya',
                'Liechtenstein',
                'Lithuania',
                'Luxembourg',
                'Macau',
                'Macedonia',
                'Madagascar',
                'Malawi',
                'Malaysia',
                'Maldives',
                'Mali',
                'Malta',
                'Marshall Islands',
                'Martinique',
                'Mauritania',
                'Mauritius',
                'Mayotte',
                'Mexico',
                'Micronesia, Federated States of',
                'Moldova',
                'Monaco',
                'Mongolia',
                'Montenegro',
                'Montserrat',
                'Morocco',
                'Mozambique',
                'Myanmar',
                'Namibia',
                'Nauru',
                'Nepal',
                'New Caledonia',
                'New Zealand',
                'Nicaragua',
                'Niger',
                'Nigeria',
                'Niue',
                'Norfolk Island',
                'North Korea',
                'Northern Mariana Islands',
                'Norway',
                'Oman',
                'Pakistan',
                'Palau',
                'Palestine, State of',
                'Panama',
                'Papua New Guinea',
                'Paraguay',
                'Peru',
                'Philippines',
                'Pitcairn',
                'Poland',
                'Portugal',
                'Puerto Rico',
                'Qatar',
                'Romania',
                'Russian Federation',
                'Rwanda',
                'RÈunion',
                'Saint BarthÈlemy',
                'Saint Helena',
                'Saint Kitts and Nevis',
                'Saint Lucia',
                'Saint Vincent and the Grenadines',
                'Saint-Martin (France)',
                'Samoa',
                'San Marino',
                'Sao Tome and Principe',
                'Saudi Arabia',
                'Senegal',
                'Serbia',
                'Seychelles',
                'Sierra Leone',
                'Singapore',
                'Sint Maarten (Dutch part)',
                'Slovakia',
                'Slovenia',
                'Solomon Islands',
                'Somalia',
                'South Africa',
                'South Georgia and the South Sandwich Islands',
                'South Korea',
                'South Sudan',
                'Spain',
                'Sri Lanka',
                'St. Pierre and Miquelon',
                'Sudan',
                'Suriname',
                'Svalbard and Jan Mayen Islands',
                'Swaziland',
                'Sweden',
                'Switzerland',
                'Syria',
                'Taiwan',
                'Tajikistan',
                'Tanzania',
                'Thailand',
                'The Netherlands',
                'Timor-Leste',
                'Togo',
                'Tokelau',
                'Tonga',
                'Trinidad and Tobago',
                'Tunisia',
                'Turkey',
                'Turkmenistan',
                'Turks and Caicos Islands',
                'Tuvalu',
                'Uganda',
                'Ukraine',
                'United Arab Emirates',
                'United Kingdom',
                'United States',
                'United States Minor Outlying Islands',
                'Uruguay',
                'Uzbekistan',
                'Vanuatu',
                'Vatican',
                'Venezuela',
                'Vietnam',
                'Virgin Islands (British)',
                'Virgin Islands (U.S.)',
                'Wallis and Futuna Islands',
                'Western Sahara',
                'Yemen',
                'Zambia',
                'Zimbabwe'
            ]
        };
    }

    render() {
        return (
            <div className='ui-spread-even'>
                <div>
                    <h5>Starts-with matching</h5>
                    <p>Please enter your country of origin:</p>
                    <UITypeahead entities={this.state.countries}
                                 showHint={true} />
                </div>
                <div style={{marginLeft: '1em'}}>
                    <h5>Fuzzy matching</h5>
                    <p>Please enter your country of origin:</p>
                    <UITypeahead entities={this.state.countries}
                                 showHint={true}
                                 matchFunc={this.fuzzyMatch.bind(this)}
                                 markFunc={this.markMultiple.bind(this)} />
                </div>
            </div>
        );
    }

    fuzzyMatch(userText, entities) {
        return entities.reduce(function findIndices(result, value, index) {
            return value.indexOf(userText) !== -1 ? (result.push(index) && result) : result;
        }, []);
    }

    markMultiple(entity, userText) {
        let frags = entity.split(new RegExp(_.escapeRegExp(userText), 'ig'));
        let threshold = frags.length - 1;
        let i = -1;
        let formed = [];

        while (++i < threshold) {
            formed.push(frags[i], <mark className='ui-typeahead-match-highlight'>{userText}</mark>);
        }

        formed.push(frags[i]); // last piece

        return formed;
    }
}
