import UITokenizedInput from '../index';
import UIView from '../../UIView';
import React from 'react';

export default class UITokenizedInputDemo extends UIView {
    initialState() {
        return {
            countries: [
                {content: 'Afghanistan'},
                {content: 'Albania'},
                {content: 'Algeria'},
                {content: 'American Samoa'},
                {content: 'Andorra'},
                {content: 'Angola'},
                {content: 'Anguilla'},
                {content: 'Antarctica'},
                {content: 'Antigua and Barbuda'},
                {content: 'Argentina'},
                {content: 'Armenia'},
                {content: 'Aruba'},
                {content: 'Australia'},
                {content: 'Austria'},
                {content: 'Azerbaijan'},
                {content: 'Bahamas'},
                {content: 'Bahrain'},
                {content: 'Bangladesh'},
                {content: 'Barbados'},
                {content: 'Belarus'},
                {content: 'Belgium'},
                {content: 'Belize'},
                {content: 'Benin'},
                {content: 'Bermuda'},
                {content: 'Bhutan'},
                {content: 'Bolivia'},
                {content: 'Bosnia and Herzegovina'},
                {content: 'Botswana'},
                {content: 'Bouvet Island'},
                {content: 'Brazil'},
                {content: 'British Indian Ocean Territory'},
                {content: 'Brunei Darussalam'},
                {content: 'Bulgaria'},
                {content: 'Burkina Faso'},
                {content: 'Burundi'},
                {content: 'Cambodia'},
                {content: 'Cameroon'},
                {content: 'Canada'},
                {content: 'Cape Verde'},
                {content: 'Caribbean Netherlands'},
                {content: 'Cayman Islands'},
                {content: 'Central African Republic'},
                {content: 'Chad'},
                {content: 'Chile'},
                {content: 'China'},
                {content: 'Christmas Island'},
                {content: 'Cocos (Keeling) Islands'},
                {content: 'Colombia'},
                {content: 'Comoros'},
                {content: 'Congo'},
                {content: 'Congo, Democratic Republic of'},
                {content: 'Cook Islands'},
                {content: 'Costa Rica'},
                {content: 'Croatia'},
                {content: 'Cuba'},
                {content: 'Curaçao'},
                {content: 'Cyprus'},
                {content: 'Czech Republic'},
                {content: 'Côte d\'Ivoire'},
                {content: 'Denmark'},
                {content: 'Djibouti'},
                {content: 'Dominica'},
                {content: 'Dominican Republic'},
                {content: 'Ecuador'},
                {content: 'Egypt'},
                {content: 'El Salvador'},
                {content: 'Equatorial Guinea'},
                {content: 'Eritrea'},
                {content: 'Estonia'},
                {content: 'Ethiopia'},
                {content: 'Falkland Islands'},
                {content: 'Faroe Islands'},
                {content: 'Fiji'},
                {content: 'Finland'},
                {content: 'France'},
                {content: 'French Guiana'},
                {content: 'French Polynesia'},
                {content: 'French Southern Territories'},
                {content: 'Gabon'},
                {content: 'Gambia'},
                {content: 'Georgia'},
                {content: 'Germany'},
                {content: 'Ghana'},
                {content: 'Gibraltar'},
                {content: 'Greece'},
                {content: 'Greenland'},
                {content: 'Grenada'},
                {content: 'Guadeloupe'},
                {content: 'Guam'},
                {content: 'Guatemala'},
                {content: 'Guernsey'},
                {content: 'Guinea'},
                {content: 'Guinea-Bissau'},
                {content: 'Guyana'},
                {content: 'Haiti'},
                {content: 'Heard and McDonald Islands'},
                {content: 'Honduras'},
                {content: 'Hong Kong'},
                {content: 'Hungary'},
                {content: 'Iceland'},
                {content: 'India'},
                {content: 'Indonesia'},
                {content: 'Iran'},
                {content: 'Iraq'},
                {content: 'Ireland'},
                {content: 'Isle of Man'},
                {content: 'Israel'},
                {content: 'Italy'},
                {content: 'Jamaica'},
                {content: 'Japan'},
                {content: 'Jersey'},
                {content: 'Jordan'},
                {content: 'Kazakhstan'},
                {content: 'Kenya'},
                {content: 'Kiribati'},
                {content: 'Kuwait'},
                {content: 'Kyrgyzstan'},
                {content: 'Lao People\'s Democratic Republic'},
                {content: 'Latvia'},
                {content: 'Lebanon'},
                {content: 'Lesotho'},
                {content: 'Liberia'},
                {content: 'Libya'},
                {content: 'Liechtenstein'},
                {content: 'Lithuania'},
                {content: 'Luxembourg'},
                {content: 'Macau'},
                {content: 'Macedonia'},
                {content: 'Madagascar'},
                {content: 'Malawi'},
                {content: 'Malaysia'},
                {content: 'Maldives'},
                {content: 'Mali'},
                {content: 'Malta'},
                {content: 'Marshall Islands'},
                {content: 'Martinique'},
                {content: 'Mauritania'},
                {content: 'Mauritius'},
                {content: 'Mayotte'},
                {content: 'Mexico'},
                {content: 'Micronesia, Federated States of'},
                {content: 'Moldova'},
                {content: 'Monaco'},
                {content: 'Mongolia'},
                {content: 'Montenegro'},
                {content: 'Montserrat'},
                {content: 'Morocco'},
                {content: 'Mozambique'},
                {content: 'Myanmar'},
                {content: 'Namibia'},
                {content: 'Nauru'},
                {content: 'Nepal'},
                {content: 'New Caledonia'},
                {content: 'New Zealand'},
                {content: 'Nicaragua'},
                {content: 'Niger'},
                {content: 'Nigeria'},
                {content: 'Niue'},
                {content: 'Norfolk Island'},
                {content: 'North Korea'},
                {content: 'Northern Mariana Islands'},
                {content: 'Norway'},
                {content: 'Oman'},
                {content: 'Pakistan'},
                {content: 'Palau'},
                {content: 'Palestine, State of'},
                {content: 'Panama'},
                {content: 'Papua New Guinea'},
                {content: 'Paraguay'},
                {content: 'Peru'},
                {content: 'Philippines'},
                {content: 'Pitcairn'},
                {content: 'Poland'},
                {content: 'Portugal'},
                {content: 'Puerto Rico'},
                {content: 'Qatar'},
                {content: 'Romania'},
                {content: 'Russian Federation'},
                {content: 'Rwanda'},
                {content: 'RÈunion'},
                {content: 'Saint Barthélemy'},
                {content: 'Saint Helena'},
                {content: 'Saint Kitts and Nevis'},
                {content: 'Saint Lucia'},
                {content: 'Saint Vincent and the Grenadines'},
                {content: 'Saint-Martin (France)'},
                {content: 'Samoa'},
                {content: 'San Marino'},
                {content: 'Sao Tome and Principe'},
                {content: 'Saudi Arabia'},
                {content: 'Senegal'},
                {content: 'Serbia'},
                {content: 'Seychelles'},
                {content: 'Sierra Leone'},
                {content: 'Singapore'},
                {content: 'Sint Maarten (Dutch part)'},
                {content: 'Slovakia'},
                {content: 'Slovenia'},
                {content: 'Solomon Islands'},
                {content: 'Somalia'},
                {content: 'South Africa'},
                {content: 'South Georgia and the South Sandwich Islands'},
                {content: 'South Korea'},
                {content: 'South Sudan'},
                {content: 'Spain'},
                {content: 'Sri Lanka'},
                {content: 'St. Pierre and Miquelon'},
                {content: 'Sudan'},
                {content: 'Suriname'},
                {content: 'Svalbard and Jan Mayen Islands'},
                {content: 'Swaziland'},
                {content: 'Sweden'},
                {content: 'Switzerland'},
                {content: 'Syria'},
                {content: 'Taiwan'},
                {content: 'Tajikistan'},
                {content: 'Tanzania'},
                {content: 'Thailand'},
                {content: 'The Netherlands'},
                {content: 'Timor-Leste'},
                {content: 'Togo'},
                {content: 'Tokelau'},
                {content: 'Tonga'},
                {content: 'Trinidad and Tobago'},
                {content: 'Tunisia'},
                {content: 'Turkey'},
                {content: 'Turkmenistan'},
                {content: 'Turks and Caicos Islands'},
                {content: 'Tuvalu'},
                {content: 'Uganda'},
                {content: 'Ukraine'},
                {content: 'United Arab Emirates'},
                {content: 'United Kingdom'},
                {content: 'United States'},
                {content: 'United States Minor Outlying Islands'},
                {content: 'Uruguay'},
                {content: 'Uzbekistan'},
                {content: 'Vanuatu'},
                {content: 'Vatican'},
                {content: 'Venezuela'},
                {content: 'Vietnam'},
                {content: 'Virgin Islands (British)'},
                {content: 'Virgin Islands (U.S.)'},
                {content: 'Wallis and Futuna Islands'},
                {content: 'Western Sahara'},
                {content: 'Yemen'},
                {content: 'Zambia'},
                {content: 'Zimbabwe'}
            ]
        };
    }

    render() {
        return (
            <div>
                <p>Please enter your country of origin:</p>
                    <UITokenizedInput entities={this.state.countries}
                                      hint={true} />
            </div>
        );
    }
}
